name: Génération du flux RSS Skolengo

on:

  schedule:
    - cron: "*/15 * * * *"

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Récupérer le dépôt
        uses: actions/checkout@v6

      - name: Installer Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Installer requests
        run: |
          pip install requests

      - name: Générer le flux RSS
        run: |
          python generate_rss.py

      - name: Configurer GitHub Pages
        uses: actions/configure-pages@v5

      - name: Préparer le site
        uses: actions/upload-pages-artifact@v4
        with:
          path: "."

      - name: Publier sur GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
